# Generated by Django 5.1 on 2024-08-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_paymentmodel_price_paymenttitlemodel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttitlemodel',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
